spring:
  application:
    name: spring-boot-integration-demo

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

environment:
  name: local